sudo: required
language: java
jdk:
- openjdk11
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_29e822f9d625_key -iv $encrypted_29e822f9d625_iv
  -in travis/helseci.key.enc -out travis/helseci.key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
- echo -e "machine github.com\n  login x-access-token\n  password $GH_TOKEN\n" > ~/.netrc
script:
- "./gradlew build --scan && docker build --pull -t $DOCKER_IMG_NAME:$COMMIT_SHORT
  ."
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    docker push $DOCKER_IMG_NAME:$COMMIT_SHORT

    DEPLOYMENT_JSON=<<EOF
  {
    "ref": "$COMMIT_SHORT",
    "description": "Automated deployment request from pipeline",
    "environment": "set_from_pipeline",
    "required_contexts": [],
    "payload": {
      "version": [1, 0, 0],
      "team": "tbd",
      "kubernetes": {
        "resources": []
      }
    }
  }
  EOF

    PREPROD_NAISERATOR=$(yq w nais-preprod.yaml spec.image $DOCKER_IMG_NAME:$COMMIT_SHORT | yq r -  -j)
    PREPROD_DEPLOYMENT=$(echo $DEPLOYMENT_JSON | jq '.payload.kubernetes.resources += ['$PREPROD_NAISERATOR']')
    PREPROD_DEPLOYMENT=$(echo $PREPROD_DEPLOYMENT | jq '.environment = "dev-fss"')

    curl -i -n \
      -X POST \
      -d "$PREPROD_DEPLOYMENT" \
      -H "Accept: application/vnd.github.ant-man-preview+json" \
      https://api.github.com/repos/navikt/helse-sparkel/deployments
  fi
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
  - ./triggerbuild.sh helse-e2e
env:
  global:
  - APP_NAME=sparkel
  - DOCKER_IMG_NAME=navikt/sparkel
  - GITHUB_APP_ID=19726
  - secure: j4irpt/Tmhcq2J4d3zOd0NzvqtxqQsUHugujU7qzgU69rEANx45fwhAz4mPMtv+5QGV9khQiHRyK2goIf1wmz+329I7syRlgE3esY8EBi/3/d0KE26/T94Qs06isXrrFjBwAUDQT7dFmhNcGHsrQuGFYV49onyU9bgbClXmurM0fzgUL/E6KJ4e1pMT/0jMveYj7Zk5pxD9fE8KLMw1rvqE8DNkOyJgOFrO6oAXKObPMEDAyanrkYe/VPaE2X1VosB4Da2eTt5icyq3c042Mmj6AUIw6jFNOWSJSnWtn4ox/eRMT2zi3hNApAvrNE7ejekkIg9yyTuiziipfRM0K0tN9O/+GsFGzNkzbTIeRBB8bmmIjC4My7GUBuINLE9clRnFFfy89Hzgv2EWCPbtd8KCqD4sYAQzdSP7IutDLlyrNaj+Wrhts0B0C1VYQNRjpiTgwKP9efAm2c/OrzGVXBn9UUvjzEPRm6lm3C7ECPxSYz94PqrnKP0koTVQwZzrjMvay2BJ0VKU8gnO9thexhe53+NWQeMfX9bYklQ7nYndtpb4WTLmzlAI+WMuk3NH83oq5rJNJCwlIXPEHbBv5+rU6h2WnGjo/Z1EokLkkb3QHjKX1Avt8LK9omPqk7gAuZKf5qgMomN+C7iHY3uanDfWwvxGalEZ0Ov+v5aqfR58=
  - secure: Pu5BWhY8ZH7lMSkRM/7ota5lkeh5IuXgn9Ur6OwuY9Q3c9oK9Y6doPGKixSTjAz9It93HXXTKDD/TQOtV1RvaC/ONxk3mUjxKMhJVYij/yEQ5PhWEPWAaSiPEDjR79RbBxf1ZkCy/pyhopVibEmfezj/1AOdbPtM0fZzSMFHc7qBBewBv387E+afox99QFZOofmfa0i/oRJB92zN7tsiEERazP09wWPHwntEtvZo+3oFTC81NuFOh5lfnWpFpEYH43T2eajw89xAoI1Ru7YzLIpx1Jq45KbqULmnlBRXA2llcetgmOV02HJlcSIM0lPQlRO2jk+Vt/ZEAgUG883Sx368yb8Df/ALxj9S5C0rPKa/VDvJLpP/hEwpJRX05tTPF2SGr6aI/DzAcRd2QgDw534Ix7mAJNCG573j0NkU7H+jKFtkD0mZjzz4N5OFtmI8dq4GUu5xROBn2grRy/pDRFT2AebfHiT0skloAUG4egXXWSk/9EOjCGaCiIuSLkB9uYhTaIPKQxcEyJJeeKKqVQehbTPssVNGzEEwzwOAE+P7ZCqJzhJKKijxb5OUkbe5IXvHmKSTW1tMtxEXtWCBCIE1pPsUV96AUg6Yxd/VoGytL9oo5i5NYfIpRUpjrH/KuXZApbGdV5q3uGauHiZpcP7d4Z5y4BBqfe8DBWmCm9c=
  - secure: ZLq1oiEbAGj/Z9XjtmV8gXdu8DREt4O94nKd9q7RytPRiVcLcK2sJ+iK+V2yqsKVVgMcDDtzzj6A71NZCzAuxROOqQ8l7SHtRY/m+nooVUz+ZRKltUj89xdRpcxWylw2W6wvS1zFi9dvY7pG/QKr062sxLmun9GlBiSp4XAZV3xFu60bnW2fvYlYRMsm51TDPEHjn6BxdzpxGJQ3zkGS2E4YWslGM8qgvScdHv8M4BMEm0hMgzHjbL2jkWWTWf3ur/fmNHlaWcfIkSsacV0h7oq4JYUnhW/sePftQ7wxFuRt4HBlpA+f2vK9Op2m24m6zVvIOexunXR8RuoorrUymDVXOJg+3KZtS0KR8+Q+MdqnqiJu6aLp9SQ00pFjHZISTlwQ9ecclu47lYIhMd6WAeAan8rf9a+I9UT8wgLVmHrh37KWc7VaN3DRUBregFY8TDWfoSSC/w9TuTSNTu+iS4+u+F//Ow7Smccni1H1DVKRSj/jeZJF5f/+D6ff5onq0YLpgtx5LkKF0hTtAiTG2LoqaBDN0+cTbo2SkwlVwZYRVo8o56fNhcefh9EAh04M/cDMFn+ZR2eSv3bESsepCm0dmqhVDHeUm5Ou3iYUm3yB58dKsMZOT11po1yXLr1o1aXqE4N6AaYJGwZhgUxCDZDTd4pvAssoxk57K6jLHJA=
notifications:
  slack:
    secure: Lx2JBWWBZBzGkKQXI5OKEurEciRUa15EfFEWYsdsjb8FM2aTGmSfjKHJOY+hpsg30pBod0jdhJ2PyPmCo5eBNPONdDM1pd4evjlwijljb+MICcOhPYCTWFTKYkKeoSCtBQ4kyw+GW+Hcw1PTGEJHS/PuIszguSrmtGiREgkzJAiNksaU21b4ARbUSF3I2pG1mbgHvFCRFUSdq5AG04rXprLfpVu0ghuK2lSx74kD9qrV8/6Sv60WBdHIPGJbAPX6kCah+aNcSLqjejELjktogHYQNRsTkSlgX0ngd0H68AOqt6tkkg2WMKEXsjHlIx11qhZ70Ln3ZG+nT9UYJ5VpowGzkHb1v2McBBXIRXz5t7Fdjq1lupYxIoj4sS23TbY0zgnpaO53PB7nPpZzwZGHVV0snkLbVymsJUQ1Cc35N05k+Z5jWnJ+JXm/MsPhuxGrTrXY4j2MlBDB3JTXaswI7E2sZtMXeysKGNiah+AZQ8Bn8HzGQB81U0CMlCkFBkK/f0GqIpb9YbmLlZCkXBOk6DU5uUtuzHVDAuFXtbnlBdmbcpxW30mzAihwLDor1KfAfLJbhFBRklho60mzc2oxGrHUlzxG/bewJlfO+Ak+rYsj5NMVmckGGCUNmd+toA9f32ww4ISKiksnoWuBMUQQzKoSvT/qpR0GOrYg8BfsQyk=
